var powder = "lal mirch powder";
powder = "haldi";
console.log("hello");
console.log(powder);
var fulName = "Hamzah";
fulName = "okasha";
fulName = "ali";
fulName = "hamzah";
console.log(fulName);
var fulNam = "hamzah syed";
var age = 22;
var bulb = true;
var bulb2 = false;
fulName;
console.log(fulNam);
fulNam = "hamzah";
var firstName = "hamzah";
var lastName = "syed";
console.log(firstName + "" + lastName);
console.log("my name is ".concat(firstName, " ").concat(lastName));
var qty = 8;
console.log(qty + 10);
console.log(qty - 1);
console.log(qty * 12000);
console.log(qty * 12000);
console.log(qty / 3);
var str1 = "1";
var str2 = "2";
console.log(str1 + str2);
var n1 = 2;
var n2 = 3;
console.log(Math.pow(n1, n2));
console.log(qty % 3);
var Age = 22;
Age += 10;
age -= 10;
console.log(age);
var n = 5;
console.log(n);
5;
n += 5;
console.log(n);
10;
n -= 5;
console.log(n);
5;
var aage = 22;
console.log(age == 22);
console.log(age === 22);
console.log(age != 22);
console.log(age > 10);
console.log(age <= 22);
var N = 5;
console.log(n == 5);
true;
console.log(n === 5);
true;
console.log(n != 5);
false;
console.log(n > 8);
false;
console.log(n < 5);
false;
console.log(n >= 8);
false;
console.log(n < 8);
true;
